### PR TITLE
Fix enum type aliasing issue

### LINKED ISSUE #9: Enums cause type-punning issue
This XML structure:

```xml
<packet ePacketType = "PAKCS_EQUIP_ITEM_RIDE">
    <includeXml path = "equipped_position_ride.xml" />
    
    <element name = "slot" type = "EquippedPositionRide" />
    <element name = "index" type = "uint16_t" />
</packet>
```

```xml
<simpleType name = "EquippedPositionRide">
    <restriction base = "uint16_t">
        <enumeration value = "BODY" />
        <enumeration value = "ENGINE" />
        <enumeration value = "LEG" />
        <enumeration value = "ABILITY" />
        <enumeration value = "ARM" />
    </restriction>
</simpleType>
```

Ends up causing an error on GCC8:

```
gen/packets/cli_equip_item_ride.cpp: In constructor ‘RoseCommon::Packet::CliEquipItemRide::CliEquipItemRide(RoseCommon::CRoseReader)’:
gen/packets/cli_equip_item_ride.cpp:11:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     if (!reader.get_uint16_t((uint16_t&)slot)) {
```

The source of the issue is these lines of code:
```cpp
CliEquipItemRide::CliEquipItemRide(CRoseReader reader) : CRosePacket(reader) {
    if (!reader.get_uint16_t((uint16_t&)slot)) {
        return;
    }
    if (!reader.get_uint16_t(index)) {
        return;
    }
}
```

### PR DESCRIPTION
**Pull request by rminderhoud**
This fixes #9 by introducing a temporary variable to use as the reference to the reader get function. This should the fix  the errors/warnings about type aliasing when using enums.

Before:
```cpp
CliEquipItemRide::CliEquipItemRide(CRoseReader reader) : CRosePacket(reader) {
    if (!reader.get_uint16_t((uint16_t&)slot)) {
        return;
    }
    if (!reader.get_uint16_t(index)) {
        return;
    }
}
```

After:
```cpp

CliEquipItemRide::CliEquipItemRide(CRoseReader reader) : CRosePacket(reader) {
    uint16_t slot_temp;
    if (!reader.get_uint16_t(slot_temp)) {
        return;
    }
    slot = (EquippedPositionRide)slot_temp;
    
    if (!reader.get_uint16_t(index)) {
        return;
    }
}
```

### CODE REVIEW

File: src/codegen_source.rs [hunk 1]
```diff
@@ -153,6 +151,15 @@ impl<'a, W: Write> CodeSourceGenerator<'a, W> {
...
                             }
                         }
+                    } else if let Some(ref enum_type) = elem.enum_type() {
+                        // Introduce a temprorary variable to avoid reference aliasing issues
+                        let temp_name = format!("{}_temp", elem.name());
+                        cg!(self, "{} {};", enum_type, temp_name);
+                        self.write_if_else(&format!("!reader.get_{}({})", enum_type, temp_name), &[
+                            "return;"
+                        ], None)?;
+                        cg!(self, "{} = ({}){};", elem.name(), elem.type_(), temp_name);
```
Comment (L3nn0x) [inline src/codegen_source.rs]: Could you use `{} = static_cast<{}>({});` instead? If the compiler still complains, use `{} = reinterpret_cast<{}>({});` instead.

**Comment by L3nn0x** [comment]
Otherwise lgtm

**Review by L3nn0x — APPROVED** [review]
